USE findash;

ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE conta
  MODIFY instituicao VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE transacao
  ADD COLUMN IF NOT EXISTS usuario_id INT NULL,
  ADD COLUMN IF NOT EXISTS tipo VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS titulo VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS categoria VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS valor_previsto DECIMAL(10, 2) NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'realizado',
  ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE transacao t
JOIN conta c ON c.id = t.conta_id
SET t.usuario_id = c.usuario_id
WHERE t.usuario_id IS NULL;

UPDATE transacao SET tipo = 'despesa' WHERE tipo IS NULL;
UPDATE transacao SET titulo = COALESCE(descricao, 'Transacao') WHERE titulo IS NULL;
UPDATE transacao SET valor_previsto = valor WHERE valor_previsto IS NULL;

ALTER TABLE transacao
  MODIFY usuario_id INT NOT NULL,
  MODIFY tipo VARCHAR(20) NOT NULL,
  MODIFY titulo VARCHAR(150) NOT NULL,
  MODIFY valor_previsto DECIMAL(10, 2) NOT NULL;

ALTER TABLE transacao
  ADD CONSTRAINT fk_transacao_usuario
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id);

ALTER TABLE vencimento
  ADD COLUMN IF NOT EXISTS dataPagamento DATE NULL,
  ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE meta
  ADD COLUMN IF NOT EXISTS aporteMensal DECIMAL(10, 2) DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
